---
kind: pipeline
type: docker
name: build-amd64
platform:
  arch: amd64
  os: linux

trigger:
  event:
    - push
    - tag

steps:
  # 1) Regular branch builds (all branches)
  - name: publish-branch
    image: plugins/ecr
    when:
      event:
        - push
      branch:
        exclude:
          - main        # everything except main
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - ${DRONE_BRANCH/\//-}-linux-amd64
      create_repository: true

  # 2) main branch builds → branch tag + latest
  - name: publish-main
    image: plugins/ecr
    when:
      event:
        - push
      branch:
        - main
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - main-linux-amd64      # or ${DRONE_BRANCH/\//-}-linux-amd64
        - latest-linux-amd64    # <--- this gives you "latest" for main
      create_repository: true

  # 3) Tag builds → use the git tag as the image tag
  - name: publish-tag
    image: plugins/ecr
    when:
      event:
        - tag
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - ${DRONE_TAG}-linux-amd64   # e.g. v1.0.0-linux-amd64
      create_repository: true

---
kind: pipeline
type: docker
name: build-arm64
platform:
  arch: arm64
  os: linux

trigger:
  event:
    - push
    - tag

steps:
  - name: publish-branch
    image: plugins/ecr
    when:
      event:
        - push
      branch:
        exclude:
          - main
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - ${DRONE_BRANCH/\//-}-linux-arm64
      create_repository: true

  - name: publish-main
    image: plugins/ecr
    when:
      event:
        - push
      branch:
        - main
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - main-linux-arm64
        - latest-linux-arm64
      create_repository: true

  - name: publish-tag
    image: plugins/ecr
    when:
      event:
        - tag
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - ${DRONE_TAG}-linux-arm64
      create_repository: true
