---
name: build-and-push-multi-arch
kind: pipeline
type: docker
platform:
  os: linux
  arch: arm64

steps:
  - name: buildx-build-and-push
    image: plugins/docker:latest
    settings:
      repo: 10.228.2.36:5000/lab-mamba
      registry: 10.228.2.36:5000
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      insecure: true

      # buildx multi-arch in the plugin (no second build)
      buildx: true
      platforms:
        - linux/amd64
        - linux/arm64

      context: .
      dockerfile: Dockerfile
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}

trigger:
  branch: [main, master]
  event: [push]
