---
name: build-and-push-to-ecr
kind: pipeline
type: docker
platform:
  arch: arm64
  os: linux

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: buildx-cache
    host:
      path: /tmp/buildx-cache

steps:
  - name: ecr-login
    image: amazon/aws-cli:2.15.17
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_DEFAULT_REGION: us-west-2
      ECR_REGISTRY:
        from_secret: ecr_registry
      REPO_NAME:
        from_secret: repo_name
    commands:
      - |
        aws ecr describe-repositories --repository-names $REPO_NAME 2>/dev/null || \
          aws ecr create-repository --repository-name $REPO_NAME \
            --image-scanning-configuration scanOnPush=true \
            --encryption-configuration encryptionType=AES256
      
      # Get ECR login token
      - aws ecr get-login-password > /tmp/ecr-token

  - name: build-and-push
    image: docker:24-cli-alpine3.18
    environment:
      ECR_REGISTRY:
        from_secret: ecr_registry
      REPO_NAME:
        from_secret: repo_name
      DOCKER_BUILDKIT: "1"
      BUILDX_NO_DEFAULT_ATTESTATIONS: "1" 
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
      - name: buildx-cache
        path: /tmp/buildx-cache
    depends_on:
      - ecr-login
    commands:
      - cat /tmp/ecr-token | docker login --username AWS --password-stdin $ECR_REGISTRY
      - |
        docker buildx create \
          --driver docker-container \
          --name multiarch \
          --driver-opt network=host \
          --use 2>/dev/null || docker buildx use multiarch
      - |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --cache-from type=local,src=/tmp/buildx-cache \
          --cache-to type=local,dest=/tmp/buildx-cache-new,mode=max \
          --tag $ECR_REGISTRY/$REPO_NAME:latest \
          --tag $ECR_REGISTRY/$REPO_NAME:$DRONE_COMMIT_SHA \
          --push \
          --progress=plain \
          .
      # Rotate cache to prevent unlimited growth
      - rm -rf /tmp/buildx-cache
      - mv /tmp/buildx-cache-new /tmp/buildx-cache || true

trigger:
  branch:
    - main
  event:
    - push
