---
kind: pipeline
type: docker
name: build-amd64
platform:
  arch: amd64
  os: linux

steps:
  - name: publish
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region:
        us-west-2
      tags:
        - ${DRONE_BRANCH/\//-}-linux-amd64
      cache_from:
        - ${ecr_registry}/${repo_name}:${DRONE_BRANCH/\//-}-linux-amd64
        - ${ecr_registry}/${repo_name}:main-linux-amd64
      create_repository: true

---
kind: pipeline
type: docker
name: build-arm64
platform:
  arch: arm64
  os: linux

steps:
  - name: publish
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region:
        us-west-2
      tags:
        - ${DRONE_BRANCH/\//-}-linux-arm64
      cache_from:
        - ${ecr_registry}/${repo_name}:${DRONE_BRANCH/\//-}-linux-arm64
        - ${ecr_registry}/${repo_name}:main-linux-arm64
      create_repository: true

