---
name: build-test
kind: pipeline
type: docker
platform:
  arch: arm64  # ← Changed from amd64 to arm64 (so it can run)
  os: linux
steps:
  - name: build-only
    image: plugins/docker
    settings:
      repo: 10.228.2.36:5000/lab-mamba
      tags: ["pr"]
      registry: 10.228.2.36:5000
      insecure: true
      dry_run: true
trigger:
  event:
    - pull_request

---
name: multi-platform
kind: pipeline
type: docker
platform:
  arch: arm64
  os: linux
steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: 10.228.2.36:5000/lab-mamba
      registry: 10.228.2.36:5000
      insecure: true
      tags: [latest, "${DRONE_COMMIT_SHA:0:8}"]
      platforms:
        - linux/amd64
        - linux/arm64
trigger:
  branch:
    - main
    - master