kind: pipeline
type: docker
name: build-multi
platform:
  arch: arm64  # ← Add this - match your runner
  os: linux

steps:
- name: build-multi-arch
  image: docker:dind
  volumes:
    - name: docker-sock
      path: /var/run/docker.sock
  commands:
    - export DOCKER_BUILDKIT=1
    - docker buildx create --use --name multiarch --driver-opt network=host || true
    - docker buildx build --platform linux/amd64,linux/arm64 -t 10.228.2.36:5000/lab-mamba:latest --output type=registry,registry.insecure=true --push .

trigger:
  branch:
    - main
    - master