---
name: build-and-push-multi-arch
kind: pipeline
type: docker
platform:
  os: linux
  arch: arm64

steps:
  - name: buildx-build-and-push
    # Pin a recent plugin with buildx baked in (works on arm64)
    image: plugins/docker:24.0
    privileged: true
    settings:
      repo: 10.228.2.36:5000/lab-mamba
      registry: 10.228.2.36:5000
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      insecure: true

      # real multi-arch
      buildx: true
      platforms:
        - linux/amd64
        - linux/arm64

#      # local/insecure registries sometimes fail on these extras
#      sbom: false
#      provenance: false

      context: .
      dockerfile: Dockerfile
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}

trigger:
  branch: [main, master]
  event: [push]
