kind: pipeline
type: docker
name: build-multi

steps:
- name: build-and-push
  image: thegeeklab/drone-docker-buildx:24.1.3
  privileged: true
  settings:
    repo: 10.228.2.36:5000/lab-mamba
    registry: 10.228.2.36:5000
    privileged: true
    insecure: true
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
    platforms:
      - linux/amd64
      - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
    - main
    - master
  event:
    - push        # build only on pushes; add tag/pull-request if desired
