---
name: build-and-push-multi-arch
kind: pipeline
type: docker
platform:
  os: linux
  arch: arm64

steps:
  - name: buildx-push
    image: docker:24.0-cli
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      REG_USER:
        from_secret: docker_username
      REG_PASS:
        from_secret: docker_password
    commands:
      - |
        set -eu
        # Allow HTTP/insecure for your registry
        cat > buildkitd.toml <<'EOF'
        [registry."10.228.2.36:5000"]
          http = true
          insecure = true
        EOF

        # Login (quiet)
        if [ -n "${REG_USER:-}" ]; then
          printf "%s" "$REG_PASS" | docker login 10.228.2.36:5000 -u "$REG_USER" --password-stdin >/dev/null 2>&1
        fi

        # Create & bootstrap builder (quiet)
        docker buildx create --name multiarch --use --driver docker-container --config ./buildkitd.toml --driver-opt network=host >/dev/null 2>&1 || true
        docker buildx inspect --bootstrap >/dev/null 2>&1

        # Short SHA tag
        SHA8="$(printf "%s" "$DRONE_COMMIT_SHA" | cut -c1-8)"

        # Build & push multi-arch manifest directly (minimal logs)
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t 10.228.2.36:5000/lab-mamba:latest \
          -t 10.228.2.36:5000/lab-mamba:$SHA8 \
          --push \
          --progress=plain \
          .

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch: [main, master]
  event: [push]
