---
kind: pipeline
type: docker
name: build-amd64
platform:
  arch: amd64
  os: linux

trigger:
  event:
    - push
    - tag

steps:
  - name: build-test-image
    image: plugins/docker
    settings:
      repo:
        lab-mamba-test
      tags:
        - ${DRONE_COMMIT_SHA}
      dry_run: true

  - name: nextflow-smoke-test
    image: nextflow/nextflow:25.10.2
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    environment:
      NXF_HOME: /tmp/nxf
      NXF_WORK: /tmp/work
    commands:
      - nextflow -version
      - |
        nextflow run ci/smoke.nf \
          -c ci/nextflow.config \
          --container lab-mamba-test:${DRONE_COMMIT_SHA} \
          --command wget --help
      - cat results/smoke/smoke_output.txt
    depends_on:
      - build-test-image

  - name: publish-branch
    image: plugins/ecr
    when:
      event:
        - push
      branch:
        exclude:
          - main
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - ${DRONE_BRANCH/\//-}-linux-amd64
      create_repository: true

  - name: publish-main
    image: plugins/ecr
    when:
      event:
        - push
      branch:
        - main
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - main-linux-amd64
        - latest-linux-amd64
        - latest
      create_repository: true

  - name: publish-tag
    image: plugins/ecr
    when:
      event:
        - tag
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - ${DRONE_TAG}-linux-amd64
      create_repository: true

---
kind: pipeline
type: docker
name: build-arm64
platform:
  arch: arm64
  os: linux

trigger:
  event:
    - push
    - tag

steps:
  - name: publish-branch
    image: plugins/ecr
    when:
      event:
        - push
      branch:
        exclude:
          - main
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - ${DRONE_BRANCH/\//-}-linux-arm64
      create_repository: true

  - name: publish-main
    image: plugins/ecr
    when:
      event:
        - push
      branch:
        - main
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - main-linux-arm64
        - latest-linux-arm64
      create_repository: true

  - name: publish-tag
    image: plugins/ecr
    when:
      event:
        - tag
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo:
        from_secret: repo_name
      registry:
        from_secret: ecr_registry
      region: us-west-2
      tags:
        - ${DRONE_TAG}-linux-arm64
      create_repository: true
