kind: pipeline
type: docker
name: build-multi

steps:
- name: build-multi-arch
  image: docker:dind
  volumes:
    - name: docker-sock
      path: /var/run/docker.sock
  commands:
    - docker buildx create --use --name multiarch --driver docker-container || echo "Builder exists"
    - docker buildx build --platform linux/amd64,linux/arm64 -t 10.228.2.36:5000/lab-mamba:latest -t 10.228.2.36:5000/lab-mamba:${DRONE_COMMIT_SHA:0:8} --push .

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
    - master
  event:
    - push