---
name: build-and-push-multi-arch
kind: pipeline
type: docker
platform:
  os: linux
  arch: arm64

steps:
  - name: buildx-push
    image: plugins/docker:latest
    privileged: true
    settings:
      repo: 10.228.2.36:5000/lab-mamba
      registry: 10.228.2.36:5000
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      insecure: true      # HTTP ok
      buildx: true        # actually use buildx/BuildKit
      context: .
      dockerfile: Dockerfile
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
    environment:
      # IMPORTANT: pass buildx flags here; this is what triggers multi-arch
      PLUGIN_BUILDX_OPTIONS_SEMICOLON: "--platform=linux/amd64,linux/arm64;--provenance=false"
      # (use _SEMICOLON when a flag contains commas)
trigger:
  branch: [main, master]
  event: [push]
