---
name: build-and-push
kind: pipeline
type: docker

steps:
  - name: build-amd64
    image: plugins/docker:24.0
    node:
      arch: amd64              # <-- schedules on the amd64-labeled runner
    settings:
      repo: 10.228.2.36:5000/lab-mamba
      registry: 10.228.2.36:5000
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      insecure: true
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DRONE_COMMIT_SHA:0:8}-amd64
        - amd64

  - name: build-arm64
    image: plugins/docker:24.0
    node:
      arch: arm64              # <-- schedules on the arm64-labeled runner
    settings:
      repo: 10.228.2.36:5000/lab-mamba
      registry: 10.228.2.36:5000
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      insecure: true
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DRONE_COMMIT_SHA:0:8}-arm64
        - arm64

  - name: publish-manifest
    image: plugins/manifest:1
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: 10.228.2.36:5000
      insecure: true
      spec: |
        image: 10.228.2.36:5000/lab-mamba:latest
        tags:
          - ${DRONE_COMMIT_SHA:0:8}
        manifests:
          - image: 10.228.2.36:5000/lab-mamba:${DRONE_COMMIT_SHA:0:8}-amd64
            platform:
              os: linux
              architecture: amd64
          - image: 10.228.2.36:5000/lab-mamba:${DRONE_COMMIT_SHA:0:8}-arm64
            platform:
              os: linux
              architecture: arm64
    depends_on:
      - build-amd64
      - build-arm64

trigger:
  branch: [main, master]
  event: [push]
