---
name: build-and-push-multi-arch
kind: pipeline
type: docker
platform:
  arch: arm64
  os: linux

steps:
  - name: build-multi-arch
    image: docker:cli
    environment:
      DOCKER_BUILDKIT: "1"
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      # 1) Write BuildKit config that marks the registry as HTTP/insecure
      - |
        cat > /root/buildkitd.toml << 'EOF'
        [registry."10.228.2.36:5000"]
          http = true
          insecure = true
        EOF

      # 2) Optional: login if your registry requires auth
      # - docker login 10.228.2.36:5000 -u "$REG_USER" -p "$REG_PASS"

      # 3) Create a dedicated builder that uses that config
      - docker buildx create --use --name multiarch --config /root/buildkitd.toml || docker buildx use multiarch

      # 4) Build and PUSH multi-arch directly (don't --load)
      - docker buildx build --platform linux/amd64,linux/arm64 -t 10.228.2.36:5000/lab-mamba:latest --push .
volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
