---
name: build-and-push-to-ecr
kind: pipeline
type: docker
platform:
  arch: arm64
  os: linux

steps:
  - name: build-and-push-ecr
    image: docker:24-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_DEFAULT_REGION: us-west-2
      ECR_REGISTRY:
        from_secret: ecr_registry
      REPO_NAME:
        from_secret: repo_name
      DOCKER_BUILDKIT: "1"
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      # Install AWS CLI in the docker image
      - apk add --no-cache aws-cli
      
      # Login to ECR
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
      
      # Create repository if it doesn't exist
      - |
        aws ecr describe-repositories --repository-names repo_name || \
          aws ecr create-repository --repository-name repo_name
      
      # Setup buildx for multi-arch
      - docker buildx create --driver docker-container --name multiarch --use || docker buildx use multiarch
      - docker buildx inspect --bootstrap
      

      - |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag $ECR_REGISTRY/repo_name:latest \
          --push \
          .

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock